application: hellow-web
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: .*  # This regex directs all routes to main.bottle
  script: hello_bottle.app


libraries:
- name: jinja2
  version: 2.6
